### ISSUE TITLE
不支持winphone8

### ISSUE THREAD

**Issue by peunzhang** [powy1993/fullpage#1]
页面在winphone8 IE10浏览器中没有效果

**Comment by powy1993** [comment]
已经对windows Phone做了兼容处理 感谢您的意见~

**Comment by peunzhang** [comment]
http://1.fullpagechris.sinaapp.com/index.html 用了这个地址做测试
在windows 8系统下IE10测试是可以了，而在winphone8手机中IE10(诺基亚lumial520)中还是不行~
虽然winphone 8用户数不是很多，但是能做适配还是好~
感谢博主的支持，你的滑屏框架是我用过体验做得比较好的，这里赞个~
