### ISSUE TITLE
如何设置锚点。或者从一个页面的a链接到指定page上？

### ISSUE THREAD

**Issue by ghost** [powy1993/fullpage#10]
如何设置锚点。或者从一个页面的a链接到指定page上？

**Comment by akafun** [comment]
var  runPage = new FullPage()  
你选择的a元素.onclick = function() {
        runPage.go(runPage.thisPage() + n);
    };  // 此处 “+” “-” 都可以,详情见demo中的js

**Comment by powy1993** [comment]
调用 runPage.go(index) 就可以了
