### ISSUE TITLE
click切换页面失效

### ISSUE THREAD

**Issue by kdocs-app** [powy1993/fullpage#15]
框架非常好用，感谢分享！
我在按钮上绑定了click事件，做页面切换。但是在点击的时候，触发了touch事件，_isLocked被设为true，此时再进行goPage，由于被锁定就直接return了。请问应该如何解决此问题？？

**Comment by powy1993** [comment]
我在邮箱中已经进行了回复~

**Comment by easyzyx** [comment]
同求

**Comment by powy1993** [comment]
将配置里面的 touch 去掉就行了！
mode : 'wheel,<b>touch,</b>nav:navBar',

加粗部分删去就可以了
