### ISSUE TITLE
当将data-step放在最后一屏时失效

### ISSUE THREAD

**Issue by dqmmpb** [powy1993/fullpage#16]
当将data-step放在最后一屏时失效，看了下代码
应该是goPage中
if (to >= pagelen || to < 0 && stepNow[indexNow] === 0) return;
当to>=pagelen时直接return了的问题吧

**Comment by dqmmpb** [comment]
当continuous设置为true时，也是会有上面的问题

**Comment by powy1993** [comment]
这个问题正在考虑修复中，感谢您的反馈，(确实是你说的原因)

您可以通过多设置一页的方式，并将那页置空，在beforeChange里面return  stop。

**Comment by shucheng** [comment]
常识了beforeChange return stop，仍然会进入到空白页面。所以如果加入空白页面 的话，空白页面要如何处理呢？

**Comment by powy1993** [comment]
你好 ，这个问题已经修复，更新版本就可以使用了

**Comment by shucheng** [comment]
对比了源码的区别，已经看到新增的判断处理。非常感谢
