### ISSUE TITLE
设置了data-step属性的容器在continuous :为true时会有bug

### ISSUE THREAD

**Issue by ialmost** [powy1993/fullpage#17]
条件：continuous:true;
属性：data-step:4
环境：PC端
场景一：next 翻页
1，第一次进入循环，从page1重新开始的时，data-step容器和step相关className不会重置（依旧是step4），并且依旧需要执行4次滑动才会进入到下一页（移动端无此问题），同时会不断的新增加step class（如：page page3 step4 step4 step4），

场景二：prev 翻页
1，第一次进入循环，从page最后一页重新开始的时候，当处在data-step容器时，依旧需要执行4次滑动才会进入到上一页（移动端无此问题）

**Comment by powy1993** [comment]
感谢你的反馈 有空的时候会进行修复
