### ISSUE TITLE
有没有终止滑动效果的方法

### ISSUE THREAD

**Issue by MaskWu** [powy1993/fullpage#2]
想问一下作者能不能在beforeChange里面进行判断  然后条件成立就终止滚动效果 执行其他动画

**Comment by powy1993** [comment]
你可以尝试在两页之间使用 '相同的背景' 在这两页内添加动画 效果也是一样的

**Comment by MaskWu** [comment]
最近看到一个滑屏的效果觉得蛮好中间还带了翻页打算实现一下 但是发现没有终止滚动的效果 所以想尝试一下

> [demo](http://dl.game.35go.net/)

**Comment by powy1993** [comment]
感谢你的建议 可能会在后续的版本中加入此功能~

**Comment by powy1993** [comment]
已经将你需要的功能整合进去了~ 感谢你的建议~

**Comment by MaskWu** [comment]
谢谢博主！

**Comment by wenzi398** [comment]
当滑动开始时,能提供一个函数来获取将要滑动到的ID吗?

**Comment by powy1993** [comment]
滑动开始的时候没有决定方向，所以不能提供 ‘将要’ 上传到的id~ 但是提供了现在正处于的位置 
onSwipeStart(indexNow);

**Comment by wenzi398** [comment]
谢谢,我再试着加入loading
