### ISSUE TITLE
关于删除touch参数，click()才能工作的问题

### ISSUE THREAD

**Issue by MaskWu** [powy1993/fullpage#20]
看到在#15中回答需要删除touch参数，但是，如果删除了touch函数，在移动端就没办法工作了，所以，想请问下还有其他的解决办法吗？

**Comment by powy1993** [comment]
如果你不需要用滑动来切屏的话可以去掉touch然后给切换的按钮添加goPage

如果你需要用滑动来切屏的话建议给需要绑定click的元素绑定touchstart或者touchend或者依然绑定click但是将touchstart不进行冒泡

**Comment by MaskWu** [comment]
好的，非常感谢，另外想请教一下，我的translate的方向是Y轴，如果在某一页里面出现了宽度过宽，需要scroll来滚动查看的话，有解决办法吗？

**Comment by powy1993** [comment]
内容你可以用 overflow:scroll; 并且将那个滚动元素的touchstart不进行冒泡，并且监听当滑动到底部的时候调用next()

**Comment by MaskWu** [comment]
好的，非常感谢

**Comment by MaskWu** [comment]
关于超出宽度用scroll的情况，添加了touch参数的话，就不能左右滚动了，阻止了touchstart的冒泡也没有解决，最后是监听了swipe的方向解决的
