### ISSUE TITLE
IE下出现闪屏问题

### ISSUE THREAD

**Issue by mrsup** [powy1993/fullpage#21]
在IE下打开页面，滑动过程中会出现闪屏问题~
请教解决方案~

**Comment by powy1993** [comment]
可否提供一下测试链接，或者使用自带demo测试一下看是否是其它因素影响

**Comment by mrsup** [comment]
@powy1993 就使用IE或者Edge浏览器打开 提供的DEMO页面http://1.fullpagechris.sinaapp.com/fullpage.html ，快速滚动鼠标滚轮都会出现闪屏~

**Comment by powy1993** [comment]
未发现这个问题，不知道是不是因为透明度的变化让你觉得闪，可以把透明度opacity:[0,1] 去掉

**Comment by mrsup** [comment]
@powy1993 我录制了一个GIF短片，你可以看一下~
http://7xplne.com1.z0.glb.clouddn.com/2_1452216920422
系win8下使用IE11浏览出现闪屏，在win10 Edge下同样出现闪屏问题，你可以迅速多次滚动鼠标滚轮可能可以重现问题，另外，附可能相关的一个问题 [jquery中当我使用了scroll事件后ie闪屏特别厉害](http://bbs.csdn.net/topics/391860604?page=1) 
另外，根据你的建议，去掉opacity，**闪屏问题就没有出现了！！！！你真乃神人也！！！十分感谢你的帮助！！！！！！**

**Comment by powy1993** [comment]
这个问题已经记录了 之后会进行具体的测试，来规避这个问题~
