### ISSUE TITLE
能否在一个网页中多次调用？

### ISSUE THREAD

**Issue by chongyuan** [powy1993/fullpage#22]
项目需求（主体部分是一个全屏切换，然后弹窗部分还有一个全屏切换）；因为想尽量减少js引入数量，所以希望两个切换都使用您这个js；
但对应两个id分别写好后，那个navbar会出问题
mode : 'wheel,touch,nav:navBar',
我原以为这个"navBar"只是导航的id，然后我把两个切换导航分别写了不同的id，可是还是不行，只有第二个能起作用，第一个失效了；

**Comment by powy1993** [comment]
可以自己写一个ul 里面自己绑定 .go(num) 跳转
