### ISSUE TITLE
我想滑动的时候有出去动画，应该在那里写方法？？

### ISSUE THREAD

**Issue by Niofh** [powy1993/fullpage#24]
1.为什么我在文字写了一个动画效果 为什么它会滑到当前页才会执行动画 是不是楼主封装号了方法？？
2.我想滑动的时候有出去动画，应该在那里写方法？？  怎么写呢？楼主！！

**Comment by powy1993** [comment]
1.是的
2.在 .swipe 里面写动画

**Comment by Niofh** [comment]
.swipe怎么你demo没写的

**Comment by Niofh** [comment]
.swipe CSS增加出场动画？？？ 为什么好像滑出去的时候没有效果呢？？
