### ISSUE TITLE
beforeChange怎么用？

### ISSUE THREAD

**Issue by skjer** [powy1993/fullpage#26]
好像加了么效果啊，callback倒是可用的

**Comment by powy1993** [comment]
我这边试了一下，是有效果的，你可以在函数内部 console.log 看看。

如果 return ‘stop’ 的话这次翻页无效，如果只是想要在切换之前做什么而不阻止，就不需要这句话

**Comment by skjer** [comment]
从GitHub下载新的已经可以了，可能我以前从别地方下的旧的，多谢多谢！
