### ISSUE TITLE
1、能不能可以默认定自义横屏或竖屏2、能不能当划完后再自动跳到第一页继续循环下去

### ISSUE THREAD

**Issue by liuyan814** [powy1993/fullpage#3]
1、能不能可以默认定自义横屏或竖屏。
2、能不能当划完后再自动跳到第一页继续循环下去。

**Comment by powy1993** [comment]
可以 在参数里可以设置
translate : 'Y',   Y是竖屏 X是横屏
continuous : true,  是继续循环
