### ISSUE TITLE
放在page内部的按钮通过事件监听触发FullPage.go()方法，并不能有效执行

### ISSUE THREAD

**Issue by gyrate** [powy1993/fullpage#38]
RT。
`$('#btn').bind('click',function(){ fullpage.go(3); }) //不能正常执行`

当前解决方法为创建周期函数不断地触发，直到正常执行。

`$('#btn').bind('click',function(){ 
` var _inter = setInterval(function () {
`if (me.myPages.thisPage() !== 3) {
`                                me.myPages.go(3);
`}else{
`                                clearInterval(_inter);
`}
`                        }, 300);
`}

**Comment by powy1993** [comment]
$('#btn').bind('click',function(){ 执行内容 })

这里面也应该用 me.myPages.go(3); 这样的吧？

**Comment by gyrate** [comment]
并不能正常地执行，必须不断点击直到成功，在android尤其明显。

**Comment by powy1993** [comment]
移动端的话要绑定 ontouchend 哦
