### ISSUE TITLE
在Mac的触控板上会出现Bug

### ISSUE THREAD

**Issue by MKFMIKU** [powy1993/fullpage#40]
滑动时只想滑一页，结果就上下晃来晃去的。。。。

**Comment by powy1993** [comment]
针对mac有做过优化哦 使用的是github下载的最新版吗？

**Comment by MKFMIKU** [comment]
http://1.fullpagechris.sinaapp.com/fullpage.html

这个demo里，会出现在第一页滑下然后连续滚动到第三页，或者到了第二页，然后自动返回第一页

**Comment by powy1993** [comment]
这个demo里面不是最新版本哦 最新版本应该没有这个问题了
