### ISSUE TITLE
step动画结束后,class里面的step要清除

### ISSUE THREAD

**Issue by luokizz** [powy1993/fullpage#43]
官方的了例子
http://1.fullpagechris.sinaapp.com/fullpage.html
我看到了这问题,step4后一直无限加step4,循环回来时已经看不到一开始的动画了
自己手动加了解决办法
callback : function(index, thisPage) { 
        	thisPage.className = thisPage.className.replace(/step.*?/g, '')
 }
另,我用那个说修复了最后一屏的js step还是失效

**Comment by powy1993** [comment]
循环模式下 末页添加 step 可能会造成无法循环 这是一个已知问题，会在之后修复。
但是这个设置是不会失效的，使用github上下载的最新版。我放在sae上的版本并不是最新的。
