### ISSUE TITLE
next(), prev()方法不起作用，怎么回事

### ISSUE THREAD

**Issue by cnyet** [powy1993/fullpage#45]
var runPage = new FullPage({
      ……    
});

runPage.next();  点击去下一页是这样用的吗？好像不起作用。

**Comment by powy1993** [comment]
新年快乐！
这么调用确实可以进入下一页的，可以在调试工具上运行一下demo.

**Comment by cnyet** [comment]
新年快乐！
你帮我看看，是这样：
<body> 
<div id="pageContain" class="page-wrap">
	<div class="page page1 current" style="background-color: green;">
		<div class="contain">
			第一屏
		</div>
	</div>
<div class="page page2" style="background-color: yellow;">
		<div class="contain">
			第二屏
		</div>
	</div>
	<div class="page page3" style="background-color: gray;">
		<div class="contain">
			第三屏
			<a href="javascript: runPage.next();">下一页</a>
		</div>
	</div>
	<div class="page page4" style="background-color: purple;">
		<div class="contain">
			第四屏
		</div>
	</div>
</div>
</body>
其他的跟你的demo是一样的，就在第三屏加个“下一页”，在chrome浏览器正常窗口下是可以跳到下一页的，但是在移动端模拟器窗口下，点击下一页是不能跳转的。你帮我看看，多谢！！

**Comment by cnyet** [comment]
新年快乐！
帮我看看，是这样的：
```
<div id="pageContain" class="page-wrap">
	<div class="page page1 current" style="background-color: green;">
		<div class="contain">
			第一屏
		</div>
	</div>
<div class="page page2" style="background-color: yellow;">
		<div class="contain">
			第二屏
		</div>
	</div>
	<div class="page page3" style="background-color: gray;">
		<div class="contain">
			第三屏
			<a href="javascript: runPage.next();">下一页</a>
		</div>
	</div>
	<div class="page page4" style="background-color: purple;">
		<div class="contain">
			第四屏
		</div>
	</div>
</div>
```
其他的都跟你的demo一样，就在第三屏加个“下一页”，在chrome正常窗口下是可以跳转的，但是在移动端模拟器窗口下，点击下一页不能跳转，你帮我看看，多谢！！

**Comment by powy1993** [comment]
不要在a的href里面运行js 在手机端绑定 ontouchstart
