### ISSUE TITLE
在safair中，滑动会重新计算高度，导致滑动时的fixed定位改变，滑动结束后恢复原来定位

### ISSUE THREAD

**Issue by LCJ-MinYa** [powy1993/fullpage#46]
该问题目前只出现在safair非全屏中，微信和uc没有该问题

**Comment by powy1993** [comment]
是手机端吗？我这边用最新的demo测试了没有此问题啊

**Comment by LCJ-MinYa** [comment]
是手机端，稍等我贴一个地址给你，你用safair试试

**Comment by LCJ-MinYa** [comment]
http://www.lichaojun.com/fullpage

**Comment by powy1993** [comment]
我感觉似乎是你没有设置body宽度的问题，试着设置一下body的宽度为屏幕宽度而不是100%。在触摸的时候上面的1111都不换行了，你试下看看，应该是你的写法问题，和组件没有关系的~

**Comment by LCJ-MinYa** [comment]
你可以开调试工具看，html body 容器ID page 我都设置了width:100%;
至于屏幕宽度这个还没尝试过， 我先用js试试
