### ISSUE TITLE
如果page1的background是图片，由page2切换至page1的时候，page1的背景图片需要在切换完成才显示

### ISSUE THREAD

**Issue by q27488** [powy1993/fullpage#47]
如题，如图：
![1](https://cloud.githubusercontent.com/assets/17950922/23977888/e1af670c-0a2b-11e7-9d85-dfe19553729a.png)
![2](https://cloud.githubusercontent.com/assets/17950922/23977887/e1ad27a8-0a2b-11e7-80f1-79025d8859cd.png)
![3](https://cloud.githubusercontent.com/assets/17950922/23977889/e324cc1c-0a2b-11e7-9af0-671d16225c39.png)

**Comment by wl123227** [comment]
遇到同样的问题，如何解决？

**Comment by powy1993** [comment]
可以把背景图片单独用一个div放起来而不是加在 contain 上
