### ISSUE TITLE
在page1设定data-step时往回滑动时step class没有恢复

### ISSUE THREAD

**Issue by e2ghost** [powy1993/fullpage#5]
在page1设定data-step时，顺序滑动step会从空到step1 / step2……
但是往回滑动的时候旧的step class不会清除。

放在page2以后就没有这个问题。

**Comment by powy1993** [comment]
会进行修复

**Comment by e2ghost** [comment]
大概修改哪些地方呢？我只是看了源码的结构没仔细研究，是在checkStep的前后还是哪里？

**Comment by powy1993** [comment]
在checkStep里面修改，最近比较忙，忙完这一阵再来更新代码。。

**Comment by powy1993** [comment]
你好 ，已经更新源码， 4.2的版本中修复了这个bug
