### ISSUE TITLE
在360极速模式下滚动时，存在直接跳到当前页、滚动一次转屏多次的情况

### ISSUE THREAD

**Issue by zhuwenqi001** [powy1993/fullpage#51]
兼容问题：在谷歌浏览器下滚动没有问题，在360极速模式下会存在滚动体验不好的情况。多滚动几次就会有转屏突然跳转、滚动一次转屏多次的情况，请问这个怎么解决呢？

**Comment by powy1993** [comment]
请问你是 Mac 系统吗，那个鼠标有自带的多次滚动持续触发的效果，这边已经按照使用习惯截流了的。如果是 Windows 系统，我之前测试过各种浏览器的。
