### ISSUE TITLE
是否提供了destroy方法，以便动态更新页面内容重新建立效果

### ISSUE THREAD

**Issue by Tonyhark** [powy1993/fullpage#7]

**Comment by Tonyhark** [comment]
另外补充问下：当下一页滚上来的时候，原来页是不动的？效果不是整个页面滚上去，而是下一个section覆盖上来？

**Comment by powy1993** [comment]
1.初始化功能会在之后的版本中考虑
2.确实是这样的

**Comment by Tonyhark** [comment]
懂了，增加一个destroy方法是不是就可以了。

**Comment by powy1993** [comment]
在最后return 里面 返回 init 就行，不过没调试 过几天看看是否好加，如果简单的话可能会加入append等
