### ISSUE TITLE
进行3D cube变换

### ISSUE THREAD

**Issue by 337840787** [powy1993/fullpage#8]
作者你好，最近刚好打算做Fullpage然后看到你框架了，想请教下
![image](https://cloud.githubusercontent.com/assets/12134136/7344665/33a2b212-ed00-11e4-9019-4b10bf9d1d4c.png)
如果我想实现如上述专题的3D切换效果 对

``` html
trans = function(o, x, y, t) {
.........
}
```

进行修改 ok吗

**Comment by powy1993** [comment]
可以，直接修改里面的参数就行，所有动画都是这个入口，就是不兼容低版本ie了

**Comment by 337840787** [comment]
ok好的 ，谢谢

**Comment by powy1993** [comment]
像 rotate 和 scale 那样加就行了

**Comment by 337840787** [comment]
发现你的框架好像是下一个页面出现直接覆盖在了前一个页面上 所以这个cube的3D效果好像不能实现
