### ISSUE TITLE
能否对某个page设置高度？

### ISSUE THREAD

**Issue by Jack-Lo** [powy1993/fullpage#9]
能否对某个page设置高度？使得page不要全屏？

**Comment by powy1993** [comment]
不知道为什么有这种需求。。其实可以用css !important 试试。。

**Comment by Jack-Lo** [comment]
因为会有页脚，给您看个实例 http://www.smartisan.com/t1/#/overview

**Comment by powy1993** [comment]
试着添加 data-step 来加入动画来达到第一页的效果~

**Comment by Jack-Lo** [comment]
有个情况，在最后一个page加data-step，不起作用~

**Comment by powy1993** [comment]
近日会进行修复~
